### ISSUE TITLE
Finalize change logging

### ISSUE THREAD

**Issue by Heaghneyn** [nish-kishore/tidypolis#7]
Tidypolis already creates change logs for the newest download compared to the last

- [x] create change logs for finalized datasets

**Comment by nish-kishore** [comment]
NH to set up meeting on 1/24/24 with NK to discuss structure for logging

**Comment by Heaghneyn** [comment]
- [ ] creating backwards compatibility for log file, adding new variables
- [ ] creating event_types other than errors, to download function, get_polis_data
- [ ] add errors to get_polis_data
- [ ] adding logging for preprocess_cdc
- [ ] error handling for preprocess_cdc
- [ ] function to read log and process, looks at latest entries and creates report
- [ ] fx to process log to archive
