### ISSUE TITLE
❇️ Feature Request: Include SIA round number for the SIA dataset

### ISSUE THREAD

**Issue by mcuadera** [nish-kishore/tidypolis#80]
Currently, we use a K-Means algorithm to obtain the round numbers. This can often take a long time and hence, would be better suited to be included in preprocessing.

**Comment by Heaghneyn** [comment]
making the results of the clustering algorithm available as separate dfs in raw.data but not including that data attached to sia df. 

making clustering part of pre-processing with its own function

**Comment by Heaghneyn** [comment]
closing and moving into sirfunctions, clustering will be run in pre-processing and round number will be calculated and pulled in get_all_polio_data
